const longVodka = {
    id: '13196',
    name: 'Long vodka',
    instructions: "Shake a tall glass with ice cubes and Angostura, coating the inside of the glass. Por the vodka onto this, add 1 slice of lime and squeeze juice out of remainder, mix with tonic, stir and voila you have a Long Vodka",
    ingredients: [
        {name: 'Vodka', measure: '5 cl '},
        {name: 'Lime', measure: '1/2 '},
        {name: 'Angostura bitters', measure: '4 dashes '},
        {name: 'Tonic water', measure: '1 dl Schweppes '},
        {name: 'Ice', measure: '4 '},
    ],
    thumbnail:  "https://www.thecocktaildb.com/images/media/drink/9179i01503565212.jpg",
}

const longVodkaJson = {
    "idDrink": "13196",
    "strDrink": "Long vodka",
    "strDrinkAlternate": null,
    "strDrinkES": null,
    "strDrinkDE": null,
    "strDrinkFR": null,
    "strDrinkZH-HANS": null,
    "strDrinkZH-HANT": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Highball glass",
    "strInstructions": "Shake a tall glass with ice cubes and Angostura, coating the inside of the glass. Por the vodka onto this, add 1 slice of lime and squeeze juice out of remainder, mix with tonic, stir and voila you have a Long Vodka",
    "strInstructionsES": null,
    "strInstructionsDE": "Schütteln Sie ein hohes Glas mit Eiswürfeln und Angostura und beschichten Sie so die Innenseite des Glases. Den Wodka darüber gießen, 1 Scheibe Limette hinzufügen und den Saft aus dem Rest herausquetschen, mit Tonic mischen, umrühren und voila, Sie haben einen langen Wodka.",
    "strInstructionsFR": null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/9179i01503565212.jpg",
    "strIngredient1": "Vodka",
    "strIngredient2": "Lime",
    "strIngredient3": "Angostura bitters",
    "strIngredient4": "Tonic water",
    "strIngredient5": "Ice",
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "5 cl ",
    "strMeasure2": "1/2 ",
    "strMeasure3": "4 dashes ",
    "strMeasure4": "1 dl Schweppes ",
    "strMeasure5": "4 ",
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2017-08-24 10:00:12"
}


export {longVodka, longVodkaJson}
